description = "Creates a new blog post with SEO considerations and places it in the correct category folder."
prompt = """
You are an expert content creator and file manager. Your task is to create a new blog post based on the provided title and content: '{{args}}'.

Please follow these steps carefully:

1.  **Analyze the Content**: First, understand the topic of the blog post from the provided text.
2.  **Determine the Category**: Based on the topic, decide on the most suitable category for the blog post (e.g., 'azure', 'security', 'automations', 'n8n').
3.  **Categorize and Place the File**:
    *   Generate a URL-friendly slug from the blog post title.
    *   Check if a directory for the determined category exists inside the 'blogs' directory.
    *   If the category directory exists, create the new blog post file inside it (e.g., 'blogs/security/my-new-post.md').
    *   If the category directory does not exist, create the new directory first, and then create the blog post file inside it.
4.  **Generate Markdown Content**: The content of the blog post file should be in markdown format and include:
    *   A compelling meta description (150-160 characters).
    *   A list of relevant keywords for SEO.
    *   An engaging and informative tone.
    *   Placeholder sections for an Introduction, Main Content, and a Conclusion, using the provided text as the main content.
"""